INSERT INTO lanterns (id, name, role, msg, created_at) VALUES
  ('seed-engine-6',
   'Engine 6 Crew',
   'B-Shift, HFD',
   '{Sample message} Cap, you taught us how to be calm in the smoke. How to walk into a kitchen fire at 3 a.m. and find the seat of it before the family was even out the door. Every probie that comes through this house is going to learn the way you did it. Rest easy. We have it from here.',
   datetime('now', '-26 hours')),
  ('seed-joanne',
   'Joanne Yee',
   'Wife',
   'Message goes here',
   datetime('now', '-14 hours')),
  ('seed-godwin',
   'Godwin Law',
   'Son in law',
   'Message goes here',
   datetime('now', '-74 hours')),
  ('seed-andrea',
   'Andrea Lee',
   'Daughter',
   'Message goes here',
   datetime('now', '-74 hours')),
  ('seed-evan',
   'Evan Lee',
   'Son',
   'Message goes here',
   datetime('now', '-74 hours'));
